Minimal dark mode
athul/archie pull request #30
Opened 2021-06-30 01:10 UTC by RobbiNespu

Ref: https://github.com/RobbiNespu/archie/pull/4/files

Minimal dark mode archie #13

2021-06-30 05:18 UTC, athul requested changes
Hey, I tried this locally, but can't change to light mode when system theme is set to dark. Not what I had in mind though 😅 . Could you patch this to change the theme even when the system theme is set on one(dark/light)

Also remove the console logs 😄

2021-06-30 07:37 UTC, RobbiNespu commented
Hi @athul , yes as mentioned on #13 , it for using light mode `manual` or light mode `auto`, the toggle will be visible. 

there is only 1 icon which is `fa-sun` for both. Even though the icon name "sun" , It look like lamp to me. If you check the setTheme() funtion, I try replace icon with `toggle.className` but seem it not work. (that is where I left console.log) , maybe you or anyone can take alook?

But nevertheless , what I need is archive but it not likely a properly work and what people expected.

Someone else need to take care it. I not good with JS. You can give me change suggestion if you found the answer or just edit the commit and make changes

2021-06-30 07:42 UTC, RobbiNespu commented on layouts/partials/footer.html
> +  <script src="{{ .Site.BaseURL }}js/toggle.dark.js"></script>
@athul maybe need to if else logic here. So if dark mode is there, then load toggle.light.js

2021-06-30 07:45 UTC, RobbiNespu commented on layouts/partials/header.html
> +		<link disabled id="dark-mode-theme" rel="stylesheet" href="{{ $darkstyle.Permalink }}">
@athul this is where, it critical. if theme is not dark mode, we can load the dark.css, but if theme are dark should we load main.css? It sound weird to me

2021-09-29 11:20 UTC, athul commented
Hey, @RobbiNespu sorry I couldn't look more into it. I really am. But had to merge #36 since it was more concise and lesser code. Hope you can understand. 

Thanks for the PR and wishing you good luck 🤝

2021-09-29 11:20 UTC, closed without merging

2021-09-29 19:17 UTC, RobbiNespu commented
Hello [@athul](https://github.com/athul) , it fine. I am okey to close the PR #30. I also agreed PR #36 it was more concise and lesser code, perhaps much cleaner. Thanks for mention and wishing you good luck too 🤝

(Originally published at: https://robbinespu.gitlab.io/indieweb/2021-09-29-0000-comment-github-archie/)